export const colors = {
  background: '#FAF5ED',
  surface: '#FFFFFF',
  surfacePressed: '#F7F0E6',
  primary: '#C47A44',
  primaryPressed: '#AC6735',
  onPrimary: '#FFFFFF',
  textPrimary: '#422B1F',
  textSecondary: '#8A7668',
  textDisabled: '#BFAF9E',
  border: '#E8DCCC',
  borderStrong: '#DBCCBA',
  decorativeCircle: '#D9E4F0',
  error: '#B0433A',
  errorBg: '#FBEEEA',
  google: '#4285F4',
  infoBg: '#E6F0FA',
  infoText: '#4A6F94',
  badgeBg: '#FBE3D0',
  badgeText: '#A9662F',
  selectedBg: '#FBE9DA',
  selectedBorder: '#C47A44',
} as const;
